# Generated by Django 5.0.1 on 2025-09-14 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_purchase_total_price_sale_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='sold_by',
            new_name='user',
        ),
    ]
